version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  frontend:
    build:
      context: ./frontend
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
  backend:
    build:
      context: ./backend
    volumes:
      - /home/node/app/node_modules
      - ./backend:/home/node/app
