### Find all users with a given email
GET http://localhost:3050/api/auth?email=karol@karolkrol.dev

### Signup
POST http://localhost:3050/api/auth/signup
Content-Type: application/json

{
    "nick": "Karol",
    "email":  "karol1@karolkrol.dev",
    "password": "zaq1@WSX"
}

### Signin
POST http://localhost:3050/api/auth/signin
Content-Type: application/json

{
    "email":  "karol@karolkrol.dev",
    "password": "zaq1@WSX"
}

### View current user
GET http://localhost:3050/api/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiS2Fyb2wiLCJpYXQiOjE3MDYyOTAzMzQsImV4cCI6MTcwNjI5MDM0NH0.zsEG7LI__IV6UBu11mLtM9Qx_urp_iPwJ4QoC5hwK-w

### Refresh token
POST http://localhost:3050/api/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiS2Fyb2wiLCJpYXQiOjE3MDYyOTAyOTEsImV4cCI6MTcwNjg5NTA5MX0.ficNat6GzhWpmxUWacIjCdCKp3ZIb2tsKrZybDCwhPk

{
    "refreshToken":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiS2Fyb2wiLCJpYXQiOjE3MDYyOTAyOTEsImV4cCI6MTcwNjg5NTA5MX0.ficNat6GzhWpmxUWacIjCdCKp3ZIb2tsKrZybDCwhPk"
}
